disabled_rules:
  - trailing_whitespace
  - type_name
excluded:
  - Carthage
line_length: 120
type_body_length:
  - 200 # warning
  - 400 # error
function_body_length:
  - 50 # warning
  - 100 # error
variable_name_max_length:
  - 60 # warning
  - 80 # error
variable_name_min_length:
  - 1 # warning
  - 0 # error
